# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    - package-ecosystem: 'npm' # or any ecosystem like 'composer', 'pip', etc.
      directory: '/' # location of your `package.json` or other dependency files
      schedule:
          interval: 'weekly' # update check schedule (daily, weekly, etc.)
      target-branch: 'development' # set the branch to 'development' instead of 'main'
      open-pull-requests-limit: 5 # limits the number of open PRs
      assignees:
          - 'andreflor21'
      commit-message:
          prefix: 'chore(deps)' # optional: customize the commit message
      ignore:
          # ignore all GitHub linguist patch updates
          - dependency-name: 'github-linguist'
            update-types: ['version-update:semver-patch']
